### ISSUE TITLE
Bitte Repo umbenennen (relative Links..)

### ISSUE THREAD

**Issue by eMPee584** [jopi98/schulstick-homepage#1]
Moin, sorry für das issue.. habe ja dies repo geforkt und deployt unter https://fsfw-dresden.github.io/schulstick-page welche ich Christian jetzt gerne als Endpunkt für schulstick.org aufsetzen lassen würde. Allerdings sind die Links kaputt dadurch, dass dein Deployment direkt auf die Subdomain geht und das andere auf einen Unterordner. Die einfachste Lösung für uns beide wäre, wenn du dieses Repo umbenennst (ebenfalls in schulstick-page), die `baseurl` entsprechend setzt und die Pfade anpasst, siehe https://stackoverflow.com/a/19173888/200509 .. sonst müssten wir divergierende Zweige pflegen und das ist auch nicht so attraktiv 😅

**Comment by jopi98** [comment]
Sollte jetzt funktionieren! Den Image-Slider weitergemacht und so hab ich noch nicht, das kommt noch. Frohe Weihnachten! 😄
